// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/file-stream.ts";
import * as $3 from "./routes/edit/[_id].tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login/index.tsx";
import * as $6 from "./routes/profile/index.tsx";
import * as $7 from "./routes/register/index.tsx";
import * as $$0 from "./islands/EditUser.tsx";
import * as $$1 from "./islands/Navbar.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/file-stream.ts": $2,
    "./routes/edit/[_id].tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/login/index.tsx": $5,
    "./routes/profile/index.tsx": $6,
    "./routes/register/index.tsx": $7,
  },
  islands: {
    "./islands/EditUser.tsx": $$0,
    "./islands/Navbar.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
